/*
 * Uinsure.CustomerPortal.API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Uinsure.CustomerPortal.Client.Client;
using Uinsure.CustomerPortal.Client.Api;
// uncomment below to import models
//using Uinsure.CustomerPortal.Client.Model;

namespace Uinsure.CustomerPortal.Client.Test.Api
{
    /// <summary>
    ///  Class for testing RenewalsQueryApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class RenewalsQueryApiTests : IDisposable
    {
        private RenewalsQueryApi instance;

        public RenewalsQueryApiTests()
        {
            instance = new RenewalsQueryApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RenewalsQueryApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' RenewalsQueryApi
            //Assert.IsType<RenewalsQueryApi>(instance);
        }

        /// <summary>
        /// Test ApiRenewalsDetailsGet
        /// </summary>
        [Fact]
        public void ApiRenewalsDetailsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ApiRenewalsDetailsGet();
            //Assert.IsType<UinsureCustomerPortalInfrastructureQueryDTORenewalDetails>(response);
        }

        /// <summary>
        /// Test ApiRenewalsDownloadGet
        /// </summary>
        [Fact]
        public void ApiRenewalsDownloadGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ApiRenewalsDownloadGet();
            //Assert.IsType<System.IO.Stream>(response);
        }

        /// <summary>
        /// Test ApiRenewalsOptInGet
        /// </summary>
        [Fact]
        public void ApiRenewalsOptInGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ApiRenewalsOptInGet();
            //Assert.IsType<bool>(response);
        }
    }
}
