/*
 * Uinsure.CustomerPortal.API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Uinsure.CustomerPortal.Client.Model;
using Uinsure.CustomerPortal.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Uinsure.CustomerPortal.Client.Test.Model
{
    /// <summary>
    ///  Class for testing BrokerDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BrokerDetailsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BrokerDetails
        //private BrokerDetails instance;

        public BrokerDetailsTests()
        {
            // TODO uncomment below to create an instance of BrokerDetails
            //instance = new BrokerDetails();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BrokerDetails
        /// </summary>
        [Fact]
        public void BrokerDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsType" BrokerDetails
            //Assert.IsType<BrokerDetails>(instance);
        }

        /// <summary>
        /// Test the property 'BrokerCommissionRate'
        /// </summary>
        [Fact]
        public void BrokerCommissionRateTest()
        {
            // TODO unit test for the property 'BrokerCommissionRate'
        }

        /// <summary>
        /// Test the property 'NetworkCommissionRate'
        /// </summary>
        [Fact]
        public void NetworkCommissionRateTest()
        {
            // TODO unit test for the property 'NetworkCommissionRate'
        }

        /// <summary>
        /// Test the property 'SaleTypeNew'
        /// </summary>
        [Fact]
        public void SaleTypeNewTest()
        {
            // TODO unit test for the property 'SaleTypeNew'
        }

        /// <summary>
        /// Test the property 'UinsureCommissionRate'
        /// </summary>
        [Fact]
        public void UinsureCommissionRateTest()
        {
            // TODO unit test for the property 'UinsureCommissionRate'
        }

        /// <summary>
        /// Test the property 'UinsureDBApplicationSource'
        /// </summary>
        [Fact]
        public void UinsureDBApplicationSourceTest()
        {
            // TODO unit test for the property 'UinsureDBApplicationSource'
        }

        /// <summary>
        /// Test the property 'UinsureDBBrokerFirstName'
        /// </summary>
        [Fact]
        public void UinsureDBBrokerFirstNameTest()
        {
            // TODO unit test for the property 'UinsureDBBrokerFirstName'
        }

        /// <summary>
        /// Test the property 'UinsureDBBrokerLastName'
        /// </summary>
        [Fact]
        public void UinsureDBBrokerLastNameTest()
        {
            // TODO unit test for the property 'UinsureDBBrokerLastName'
        }

        /// <summary>
        /// Test the property 'UinsureDBBrokerFullName'
        /// </summary>
        [Fact]
        public void UinsureDBBrokerFullNameTest()
        {
            // TODO unit test for the property 'UinsureDBBrokerFullName'
        }

        /// <summary>
        /// Test the property 'UinsureDBCompanyName'
        /// </summary>
        [Fact]
        public void UinsureDBCompanyNameTest()
        {
            // TODO unit test for the property 'UinsureDBCompanyName'
        }

        /// <summary>
        /// Test the property 'UinsureDBDistributionGroupName'
        /// </summary>
        [Fact]
        public void UinsureDBDistributionGroupNameTest()
        {
            // TODO unit test for the property 'UinsureDBDistributionGroupName'
        }

        /// <summary>
        /// Test the property 'UinsureDBDrillDownStatus'
        /// </summary>
        [Fact]
        public void UinsureDBDrillDownStatusTest()
        {
            // TODO unit test for the property 'UinsureDBDrillDownStatus'
        }

        /// <summary>
        /// Test the property 'UinsureDBNetworkName'
        /// </summary>
        [Fact]
        public void UinsureDBNetworkNameTest()
        {
            // TODO unit test for the property 'UinsureDBNetworkName'
        }

        /// <summary>
        /// Test the property 'UinsureDBOriginalBrokerFirstName'
        /// </summary>
        [Fact]
        public void UinsureDBOriginalBrokerFirstNameTest()
        {
            // TODO unit test for the property 'UinsureDBOriginalBrokerFirstName'
        }

        /// <summary>
        /// Test the property 'UinsureDBOriginalBrokerLastName'
        /// </summary>
        [Fact]
        public void UinsureDBOriginalBrokerLastNameTest()
        {
            // TODO unit test for the property 'UinsureDBOriginalBrokerLastName'
        }

        /// <summary>
        /// Test the property 'UinsureDBOriginalBrokerFullName'
        /// </summary>
        [Fact]
        public void UinsureDBOriginalBrokerFullNameTest()
        {
            // TODO unit test for the property 'UinsureDBOriginalBrokerFullName'
        }

        /// <summary>
        /// Test the property 'UinsureDBOriginalCompanyName'
        /// </summary>
        [Fact]
        public void UinsureDBOriginalCompanyNameTest()
        {
            // TODO unit test for the property 'UinsureDBOriginalCompanyName'
        }

        /// <summary>
        /// Test the property 'UinsureDBOriginalDistributionGroupName'
        /// </summary>
        [Fact]
        public void UinsureDBOriginalDistributionGroupNameTest()
        {
            // TODO unit test for the property 'UinsureDBOriginalDistributionGroupName'
        }

        /// <summary>
        /// Test the property 'UinsureDBOriginalNetworkName'
        /// </summary>
        [Fact]
        public void UinsureDBOriginalNetworkNameTest()
        {
            // TODO unit test for the property 'UinsureDBOriginalNetworkName'
        }

        /// <summary>
        /// Test the property 'UinsureDBOriginalPolicyNumber'
        /// </summary>
        [Fact]
        public void UinsureDBOriginalPolicyNumberTest()
        {
            // TODO unit test for the property 'UinsureDBOriginalPolicyNumber'
        }

        /// <summary>
        /// Test the property 'UinsureDBSaleType'
        /// </summary>
        [Fact]
        public void UinsureDBSaleTypeTest()
        {
            // TODO unit test for the property 'UinsureDBSaleType'
        }

        /// <summary>
        /// Test the property 'UinsureDBSource'
        /// </summary>
        [Fact]
        public void UinsureDBSourceTest()
        {
            // TODO unit test for the property 'UinsureDBSource'
        }
    }
}
