/*
 * Uinsure.CustomerPortal.API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Uinsure.CustomerPortal.Client.Model;
using Uinsure.CustomerPortal.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Uinsure.CustomerPortal.Client.Test.Model
{
    /// <summary>
    ///  Class for testing Claim
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ClaimTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Claim
        //private Claim instance;

        public ClaimTests()
        {
            // TODO uncomment below to create an instance of Claim
            //instance = new Claim();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Claim
        /// </summary>
        [Fact]
        public void ClaimInstanceTest()
        {
            // TODO uncomment below to test "IsType" Claim
            //Assert.IsType<Claim>(instance);
        }

        /// <summary>
        /// Test the property 'ClaimReference'
        /// </summary>
        [Fact]
        public void ClaimReferenceTest()
        {
            // TODO unit test for the property 'ClaimReference'
        }

        /// <summary>
        /// Test the property 'InsurerName'
        /// </summary>
        [Fact]
        public void InsurerNameTest()
        {
            // TODO unit test for the property 'InsurerName'
        }

        /// <summary>
        /// Test the property 'ClaimStatus'
        /// </summary>
        [Fact]
        public void ClaimStatusTest()
        {
            // TODO unit test for the property 'ClaimStatus'
        }

        /// <summary>
        /// Test the property 'LossDate'
        /// </summary>
        [Fact]
        public void LossDateTest()
        {
            // TODO unit test for the property 'LossDate'
        }

        /// <summary>
        /// Test the property 'LossDescription'
        /// </summary>
        [Fact]
        public void LossDescriptionTest()
        {
            // TODO unit test for the property 'LossDescription'
        }

        /// <summary>
        /// Test the property 'ClaimType'
        /// </summary>
        [Fact]
        public void ClaimTypeTest()
        {
            // TODO unit test for the property 'ClaimType'
        }

        /// <summary>
        /// Test the property 'DetailedStatus'
        /// </summary>
        [Fact]
        public void DetailedStatusTest()
        {
            // TODO unit test for the property 'DetailedStatus'
        }

        /// <summary>
        /// Test the property 'ClaimSection'
        /// </summary>
        [Fact]
        public void ClaimSectionTest()
        {
            // TODO unit test for the property 'ClaimSection'
        }

        /// <summary>
        /// Test the property 'ClosedDate'
        /// </summary>
        [Fact]
        public void ClosedDateTest()
        {
            // TODO unit test for the property 'ClosedDate'
        }

        /// <summary>
        /// Test the property 'IncludeInClaimsCalculation'
        /// </summary>
        [Fact]
        public void IncludeInClaimsCalculationTest()
        {
            // TODO unit test for the property 'IncludeInClaimsCalculation'
        }

        /// <summary>
        /// Test the property 'TotalClaimCost'
        /// </summary>
        [Fact]
        public void TotalClaimCostTest()
        {
            // TODO unit test for the property 'TotalClaimCost'
        }
    }
}
