/*
 * Uinsure.CustomerPortal.API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Uinsure.CustomerPortal.Client.Model;
using Uinsure.CustomerPortal.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Uinsure.CustomerPortal.Client.Test.Model
{
    /// <summary>
    ///  Class for testing MicrosoftAspNetCoreMvcProblemDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MicrosoftAspNetCoreMvcProblemDetailsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MicrosoftAspNetCoreMvcProblemDetails
        //private MicrosoftAspNetCoreMvcProblemDetails instance;

        public MicrosoftAspNetCoreMvcProblemDetailsTests()
        {
            // TODO uncomment below to create an instance of MicrosoftAspNetCoreMvcProblemDetails
            //instance = new MicrosoftAspNetCoreMvcProblemDetails();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MicrosoftAspNetCoreMvcProblemDetails
        /// </summary>
        [Fact]
        public void MicrosoftAspNetCoreMvcProblemDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsType" MicrosoftAspNetCoreMvcProblemDetails
            //Assert.IsType<MicrosoftAspNetCoreMvcProblemDetails>(instance);
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'Detail'
        /// </summary>
        [Fact]
        public void DetailTest()
        {
            // TODO unit test for the property 'Detail'
        }

        /// <summary>
        /// Test the property 'Instance'
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO unit test for the property 'Instance'
        }
    }
}
