/*
 * Uinsure.CustomerPortal.API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Uinsure.CustomerPortal.Client.Model;
using Uinsure.CustomerPortal.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Uinsure.CustomerPortal.Client.Test.Model
{
    /// <summary>
    ///  Class for testing PolicyCover
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PolicyCoverTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PolicyCover
        //private PolicyCover instance;

        public PolicyCoverTests()
        {
            // TODO uncomment below to create an instance of PolicyCover
            //instance = new PolicyCover();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PolicyCover
        /// </summary>
        [Fact]
        public void PolicyCoverInstanceTest()
        {
            // TODO uncomment below to test "IsType" PolicyCover
            //Assert.IsType<PolicyCover>(instance);
        }

        /// <summary>
        /// Test the property 'IsFirstTimeBuyer'
        /// </summary>
        [Fact]
        public void IsFirstTimeBuyerTest()
        {
            // TODO unit test for the property 'IsFirstTimeBuyer'
        }

        /// <summary>
        /// Test the property 'BuildingsCoverAmount'
        /// </summary>
        [Fact]
        public void BuildingsCoverAmountTest()
        {
            // TODO unit test for the property 'BuildingsCoverAmount'
        }

        /// <summary>
        /// Test the property 'BuildingsAccidentalCover'
        /// </summary>
        [Fact]
        public void BuildingsAccidentalCoverTest()
        {
            // TODO unit test for the property 'BuildingsAccidentalCover'
        }

        /// <summary>
        /// Test the property 'BuildingsExcess'
        /// </summary>
        [Fact]
        public void BuildingsExcessTest()
        {
            // TODO unit test for the property 'BuildingsExcess'
        }

        /// <summary>
        /// Test the property 'BuildingsNoClaimsYears'
        /// </summary>
        [Fact]
        public void BuildingsNoClaimsYearsTest()
        {
            // TODO unit test for the property 'BuildingsNoClaimsYears'
        }

        /// <summary>
        /// Test the property 'ContentsCoverAmount'
        /// </summary>
        [Fact]
        public void ContentsCoverAmountTest()
        {
            // TODO unit test for the property 'ContentsCoverAmount'
        }

        /// <summary>
        /// Test the property 'ContentsAccidentalDamage'
        /// </summary>
        [Fact]
        public void ContentsAccidentalDamageTest()
        {
            // TODO unit test for the property 'ContentsAccidentalDamage'
        }

        /// <summary>
        /// Test the property 'ContentsExcess'
        /// </summary>
        [Fact]
        public void ContentsExcessTest()
        {
            // TODO unit test for the property 'ContentsExcess'
        }

        /// <summary>
        /// Test the property 'ContentsNoClaimYears'
        /// </summary>
        [Fact]
        public void ContentsNoClaimYearsTest()
        {
            // TODO unit test for the property 'ContentsNoClaimYears'
        }

        /// <summary>
        /// Test the property 'PersonalBelongingsCover'
        /// </summary>
        [Fact]
        public void PersonalBelongingsCoverTest()
        {
            // TODO unit test for the property 'PersonalBelongingsCover'
        }

        /// <summary>
        /// Test the property 'BuildingsNcdCurrentPolicy'
        /// </summary>
        [Fact]
        public void BuildingsNcdCurrentPolicyTest()
        {
            // TODO unit test for the property 'BuildingsNcdCurrentPolicy'
        }

        /// <summary>
        /// Test the property 'BuildingsNcdNextRenewal'
        /// </summary>
        [Fact]
        public void BuildingsNcdNextRenewalTest()
        {
            // TODO unit test for the property 'BuildingsNcdNextRenewal'
        }

        /// <summary>
        /// Test the property 'BuildingsUinsureCurrentClaimFreeTenure'
        /// </summary>
        [Fact]
        public void BuildingsUinsureCurrentClaimFreeTenureTest()
        {
            // TODO unit test for the property 'BuildingsUinsureCurrentClaimFreeTenure'
        }

        /// <summary>
        /// Test the property 'ContentsNcdCurrentPolicy'
        /// </summary>
        [Fact]
        public void ContentsNcdCurrentPolicyTest()
        {
            // TODO unit test for the property 'ContentsNcdCurrentPolicy'
        }

        /// <summary>
        /// Test the property 'ContentsNcdNextRenewal'
        /// </summary>
        [Fact]
        public void ContentsNcdNextRenewalTest()
        {
            // TODO unit test for the property 'ContentsNcdNextRenewal'
        }

        /// <summary>
        /// Test the property 'ContentsUinsureCurrentClaimFreeTenure'
        /// </summary>
        [Fact]
        public void ContentsUinsureCurrentClaimFreeTenureTest()
        {
            // TODO unit test for the property 'ContentsUinsureCurrentClaimFreeTenure'
        }

        /// <summary>
        /// Test the property 'EligibleForRebroke'
        /// </summary>
        [Fact]
        public void EligibleForRebrokeTest()
        {
            // TODO unit test for the property 'EligibleForRebroke'
        }

        /// <summary>
        /// Test the property 'OriginalInceptionDate'
        /// </summary>
        [Fact]
        public void OriginalInceptionDateTest()
        {
            // TODO unit test for the property 'OriginalInceptionDate'
        }
    }
}
