/*
 * Uinsure.CustomerPortal.API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Uinsure.CustomerPortal.Client.Model;
using Uinsure.CustomerPortal.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Uinsure.CustomerPortal.Client.Test.Model
{
    /// <summary>
    ///  Class for testing QuotePremium
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class QuotePremiumTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for QuotePremium
        //private QuotePremium instance;

        public QuotePremiumTests()
        {
            // TODO uncomment below to create an instance of QuotePremium
            //instance = new QuotePremium();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of QuotePremium
        /// </summary>
        [Fact]
        public void QuotePremiumInstanceTest()
        {
            // TODO uncomment below to test "IsType" QuotePremium
            //Assert.IsType<QuotePremium>(instance);
        }

        /// <summary>
        /// Test the property 'Provider'
        /// </summary>
        [Fact]
        public void ProviderTest()
        {
            // TODO unit test for the property 'Provider'
        }

        /// <summary>
        /// Test the property 'CreditCharge'
        /// </summary>
        [Fact]
        public void CreditChargeTest()
        {
            // TODO unit test for the property 'CreditCharge'
        }

        /// <summary>
        /// Test the property 'TotalMonthlyPremium'
        /// </summary>
        [Fact]
        public void TotalMonthlyPremiumTest()
        {
            // TODO unit test for the property 'TotalMonthlyPremium'
        }

        /// <summary>
        /// Test the property 'TotalAmountPayable'
        /// </summary>
        [Fact]
        public void TotalAmountPayableTest()
        {
            // TODO unit test for the property 'TotalAmountPayable'
        }

        /// <summary>
        /// Test the property 'LastYearsPremium'
        /// </summary>
        [Fact]
        public void LastYearsPremiumTest()
        {
            // TODO unit test for the property 'LastYearsPremium'
        }

        /// <summary>
        /// Test the property 'LastYearsPremiumWithoutPremiumFunding'
        /// </summary>
        [Fact]
        public void LastYearsPremiumWithoutPremiumFundingTest()
        {
            // TODO unit test for the property 'LastYearsPremiumWithoutPremiumFunding'
        }

        /// <summary>
        /// Test the property 'LastYearsMonthlyPremium'
        /// </summary>
        [Fact]
        public void LastYearsMonthlyPremiumTest()
        {
            // TODO unit test for the property 'LastYearsMonthlyPremium'
        }

        /// <summary>
        /// Test the property 'IsPayingMonthly'
        /// </summary>
        [Fact]
        public void IsPayingMonthlyTest()
        {
            // TODO unit test for the property 'IsPayingMonthly'
        }

        /// <summary>
        /// Test the property 'IsPremiumFunded'
        /// </summary>
        [Fact]
        public void IsPremiumFundedTest()
        {
            // TODO unit test for the property 'IsPremiumFunded'
        }
    }
}
