/*
 * Uinsure.CustomerPortal.API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Uinsure.CustomerPortal.Client.Model;
using Uinsure.CustomerPortal.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Uinsure.CustomerPortal.Client.Test.Model
{
    /// <summary>
    ///  Class for testing UinsureCustomerPortalInfrastructureQueryDTOFindPoliciesResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UinsureCustomerPortalInfrastructureQueryDTOFindPoliciesResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UinsureCustomerPortalInfrastructureQueryDTOFindPoliciesResult
        //private UinsureCustomerPortalInfrastructureQueryDTOFindPoliciesResult instance;

        public UinsureCustomerPortalInfrastructureQueryDTOFindPoliciesResultTests()
        {
            // TODO uncomment below to create an instance of UinsureCustomerPortalInfrastructureQueryDTOFindPoliciesResult
            //instance = new UinsureCustomerPortalInfrastructureQueryDTOFindPoliciesResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UinsureCustomerPortalInfrastructureQueryDTOFindPoliciesResult
        /// </summary>
        [Fact]
        public void UinsureCustomerPortalInfrastructureQueryDTOFindPoliciesResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" UinsureCustomerPortalInfrastructureQueryDTOFindPoliciesResult
            //Assert.IsType<UinsureCustomerPortalInfrastructureQueryDTOFindPoliciesResult>(instance);
        }

        /// <summary>
        /// Test the property 'PolicyNumber'
        /// </summary>
        [Fact]
        public void PolicyNumberTest()
        {
            // TODO unit test for the property 'PolicyNumber'
        }

        /// <summary>
        /// Test the property 'StartDate'
        /// </summary>
        [Fact]
        public void StartDateTest()
        {
            // TODO unit test for the property 'StartDate'
        }

        /// <summary>
        /// Test the property 'PolicyType'
        /// </summary>
        [Fact]
        public void PolicyTypeTest()
        {
            // TODO unit test for the property 'PolicyType'
        }

        /// <summary>
        /// Test the property 'PolicyStatus'
        /// </summary>
        [Fact]
        public void PolicyStatusTest()
        {
            // TODO unit test for the property 'PolicyStatus'
        }

        /// <summary>
        /// Test the property 'RiskAddress'
        /// </summary>
        [Fact]
        public void RiskAddressTest()
        {
            // TODO unit test for the property 'RiskAddress'
        }

        /// <summary>
        /// Test the property 'Applicant1'
        /// </summary>
        [Fact]
        public void Applicant1Test()
        {
            // TODO unit test for the property 'Applicant1'
        }

        /// <summary>
        /// Test the property 'Applicant2'
        /// </summary>
        [Fact]
        public void Applicant2Test()
        {
            // TODO unit test for the property 'Applicant2'
        }

        /// <summary>
        /// Test the property 'DateOfBirth'
        /// </summary>
        [Fact]
        public void DateOfBirthTest()
        {
            // TODO unit test for the property 'DateOfBirth'
        }

        /// <summary>
        /// Test the property 'DataQualityIssueFlag'
        /// </summary>
        [Fact]
        public void DataQualityIssueFlagTest()
        {
            // TODO unit test for the property 'DataQualityIssueFlag'
        }

        /// <summary>
        /// Test the property 'PolicyIssueFlag'
        /// </summary>
        [Fact]
        public void PolicyIssueFlagTest()
        {
            // TODO unit test for the property 'PolicyIssueFlag'
        }
    }
}
