/*
 * Uinsure.CustomerPortal.API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Uinsure.CustomerPortal.Client.Model;
using Uinsure.CustomerPortal.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Uinsure.CustomerPortal.Client.Test.Model
{
    /// <summary>
    ///  Class for testing UinsureCustomerPortalInfrastructureQueryDTOSpecifiedItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UinsureCustomerPortalInfrastructureQueryDTOSpecifiedItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UinsureCustomerPortalInfrastructureQueryDTOSpecifiedItem
        //private UinsureCustomerPortalInfrastructureQueryDTOSpecifiedItem instance;

        public UinsureCustomerPortalInfrastructureQueryDTOSpecifiedItemTests()
        {
            // TODO uncomment below to create an instance of UinsureCustomerPortalInfrastructureQueryDTOSpecifiedItem
            //instance = new UinsureCustomerPortalInfrastructureQueryDTOSpecifiedItem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UinsureCustomerPortalInfrastructureQueryDTOSpecifiedItem
        /// </summary>
        [Fact]
        public void UinsureCustomerPortalInfrastructureQueryDTOSpecifiedItemInstanceTest()
        {
            // TODO uncomment below to test "IsType" UinsureCustomerPortalInfrastructureQueryDTOSpecifiedItem
            //Assert.IsType<UinsureCustomerPortalInfrastructureQueryDTOSpecifiedItem>(instance);
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

        /// <summary>
        /// Test the property 'CoverAtHome'
        /// </summary>
        [Fact]
        public void CoverAtHomeTest()
        {
            // TODO unit test for the property 'CoverAtHome'
        }

        /// <summary>
        /// Test the property 'CoverAwayFromHome'
        /// </summary>
        [Fact]
        public void CoverAwayFromHomeTest()
        {
            // TODO unit test for the property 'CoverAwayFromHome'
        }
    }
}
